development:
  scheme: <%=config[:product_name]%>
  configuration: Debug
  sdk: iphonesimulator

test:
  scheme: <%=config[:product_name]%>
  configuration: Debug
  sdk: iphonesimulator

adhoc:
  scheme: <%=config[:product_name]%>
  configuration: Debug
  sdk: iphoneos
  profile: Your Profile         # replace with your profile
  testflight_distribution_lists:
    - YourList                  # replace with your distlist
      
production:
  scheme: <%=config[:product_name]%>
  configuration: Release
  sdk: iphoneos