name: <%=config[:product_name]%>
testflight_api_team_token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'      # replace with your own token
code_signing_identity: 'iPhone Distribution: iPhone Developper' # replace with your code sige 
